version: "3.7"
services:
  frontend:
    build: ./frontend
    image: lisandrodv27/frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend:
    build: ./backend
    image: lisandrodv27/backend:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
