version: "3.6"
services:
  frontend:
    build: ./frontend
    image: lisandrodv27/frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend:
    build: ./backend
    image: lisandrodv27/backend:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI=mysql+pymysql://root:password123@main-db.cpe0zmxz843f.eu-west-1.rds.amazonaws.com:3306/users
      TEST_DATABASE_URI=mysql+pymysql://root:password123@:test-db.cpe0zmxz843f.eu-west-1.rds.amazonaws.com:3306/testdb
