apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev-ops-project
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: lisandrodv27/backend-build:latest
        imagePullPolicy: "Always"
        ports: 
        - containerPort: 5001
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: k8s-credentials
              key: DATABASE_URI
        - name: TEST_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: k8s-credentials
              key: TEST_DATABASE_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: k8s-credentials
              key: SECRET_KEY
