apiVersion: v1
kind: Service
metadata:
  name: cl-ip-back
  namespace: dev-ops-project
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
                 
