apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: dev-ops-project
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
